export const LOAD_CALENDAR_REQUEST = 'LOAD_CALENDAR_REQUEST';
export const LOAD_CALENDAR_SUCCESS = 'LOAD_CALENDAR_SUCCESS';
export const LOAD_CALENDAR_FAILURE = 'LOAD_CALENDAR_FAILURE';

export const SET_NOW_TRIP = 'SET_NOW_TRIP';
export const SET_NOW_DATE = 'SET_NOW_DATE';







