export const SET_NAVS_CURRENT_ROUTE = 'SET_NAVS_CURRENT_ROUTE';
export const SET_NAVS_CURRENT_ITEMS = 'SET_NAVS_CURRENT_ITEMS';
export const SET_NAVS_CURRENT_ITEM_ACTIVE = 'SET_NAVS_CURRENT_ITEMS_ACTIVE';

export const SET_NAVS_ACTIVITY = 'SET_NAVS_ACTIVITY';






